[project]
name = "personamail-backend"
version = "0.1.0"
dependencies = []

[tool.pyrefly]
python_interpreter = "C:/Users/ezrxe/OneDrive/Documents/GitHub/personamail/backend/venv/Scripts/python.exe"
search_paths = [
    ".",
    "venv/Lib/site-packages",
    "C:/Users/ezrxe/OneDrive/Documents/GitHub/personamail/backend",
    "C:/Users/ezrxe/OneDrive/Documents/GitHub/personamail/backend/venv/Lib/site-packages"
]
exclude = [
    "**/__pyrefly_virtual__/**",
    "**/inmemory/**",
    "c:/__pyrefly_virtual__/**",
    "C:/__pyrefly_virtual__/**"
]

[tool.pyright]
venvPath = "."
venv = "venv"
extraPaths = [
    ".",
    "venv/Lib/site-packages",
    "C:/Users/ezrxe/OneDrive/Documents/GitHub/personamail/backend",
    "C:/Users/ezrxe/OneDrive/Documents/GitHub/personamail/backend/venv/Lib/site-packages"
]
